### ISSUE TITLE
Wifi connection errors

### ISSUE THREAD

**Issue by Woffkaa** [johnlife/Glimpse-Android#62]
**we need you to test this one in at least 3 distinct wi-fi environments, because it does not occur in all wi-fi environments** Currently, when you choose a wi-fi network, we STILL sometimes encounter a very confusing flow: “Wi-fi connecting” message will appear, then disappear, and the wi-fi list stays on the screen for 3-5 seconds with no other prompt. Then it finally connects to the wi-fi network, and reveals the “successfully connected” prompt. But the 3-5 seconds when “wi-fi connecting” message is gone and “successfully connected” message has not come up makes people think that something went wrong. The way this should work is: user selects wi-fi —> “wi-fi connecting” message stays on screen until the very moment that the device connects or fails to connect —> the “successfully connected” message appears (or the “failed to connect” message if connection fails). There should never be a time after you choose a network when the screen just shows the wi-fi list and nothing else.

**Comment by alexrodobolsky** [comment]
Сдедано
