### ISSUE TITLE
Получение адреса на неинициализированную рамку по коду

### ISSUE THREAD

**Issue by johnlife** [johnlife/Glimpse-Android#69]
**Frontend**
When you open up Skylight for the first time and connect to wifi, you get to the code entry screen. 

This consists of:
* A prompt. It says “Please enter your personal Skylight code. If you don’t have your code, email info@skylightframe.com.”
* A EditText – this is where the user’s code will display as they enter it.
* The Android keyboard, pre-set to the numbers input

Once the user enters the entire 6-digit code, they do not need to press enter. The app immediately pings our server with that code and displays progress instead of EditText.
If the code is associated with a Skylight email address: the app pulls down the associated Skylight email address and pastes it into userdata.txt. It then takes you to the normal Skylight welcome screen that says something like “To start, please send photos to [email address].”

If the code is not associated with a Skylight email address, hide, progress, reveal EditText back and return a pop-up: “Your code is not recognized. Try again or email info@skylightframe.com for help.” This pop-up should appear at the top of the screen for (roughly) 10 seconds. 

Once a code is recognized and userdata.txt is programmed, the app should never ask you for the code again. Userdata.txt is now hard-coded, no matter how often you restart Skylight.

**Backend**
We simply need a field associated with each of our Skylight email addresses, into which we can put a 6 digit code. This is the field that the front-end will check in the above system.

When you add a skylight frame email to backend, a code is automatically generated.The code is unique at the moment of generation.

Once a code is used and a device pulls down a certain email, the code is deleted from the system. Therefore, if someone tries to use the code after it’s been used, it will be rejected.

Admin UI should provide ability to re-generate a code for an address where the code has already been used.

**Comment by Woffkaa** [comment]
Сделано
