### ISSUE TITLE
Таки что-то не так с кодировкой аттачментов

### ISSUE THREAD

**Issue by johnlife** [johnlife/Glimpse-Android#73]
Error in encoded stream: needed 4 valid base64 characters but only got 2 before EOF, the 10 most recent characters were: "69\r\nvWgQ4S"
    java.io.IOException: Error in encoded stream: needed 4 valid base64 characters but only got 2 before EOF, the 10 most recent characters were: "69\r\nvWgQ4S"
            at com.sun.mail.util.BASE64DecoderStream.decode(BASE64DecoderStream.java:250)
            at com.sun.mail.util.BASE64DecoderStream.read(BASE64DecoderStream.java:148)
            at java.io.InputStream.read(InputStream.java:162)

**Comment by johnlife** [comment]
Про /r/n - Я в гмыле фотки вставляю прямо в тело письма. Может это как-то поможет

**Comment by Woffkaa** [comment]
гугл
09-17 10:54:05.010  13059-13083/odesk.johnlife.glimpse I/System.out﹕ * 1 FETCH (BODYSTRUCTURE ((("text" "plain" ("charset" "UTF-8") NIL NIL "7bit" 2 1 NIL NIL NIL NIL)("text" "html" ("charset" "UTF-8") NIL NIL "7bit" 27 1 NIL NIL NIL NIL) "alternative" ("boundary" "001a113dc8b86ab6b3051fecb758") NIL NIL NIL)("image" "jpeg" ("name" "images.jpg") NIL NIL "base64" 7981 NIL ("attachment" ("filename" "images.jpg")) NIL NIL) "mixed" ("boundary" "001a113dc8b86ab6bc051fecb75a") NIL NIL NIL))
09-17 10:54:05.010  13059-13083/odesk.johnlife.glimpse I/System.out﹕ A4 OK Fetch completed.
09-17 10:54:05.285  13059-13083/odesk.johnlife.glimpse D/MailConnector﹕ Found 0 attachments.
09-17 10:54:05.295  13059-13083/odesk.johnlife.glimpse I/System.out﹕ A5 FETCH 1 (BODY[2]<0.7981>)
09-17 10:54:05.380  13059-13083/odesk.johnlife.glimpse I/System.out﹕ * 1 FETCH (FLAGS (\Seen \Recent) BODY[2]<0> {7981}



яндекс
09-17 11:06:56.255  13059-16087/odesk.johnlife.glimpse I/System.out﹕ * 1 FETCH (BODYSTRUCTURE (("image" "jpeg" ("name" "images.jpg") NIL NIL "base64" 9688 NIL ("attachment" ("filename" "images.jpg")) NIL NIL) "mixed" ("boundary" "----==--bound.38660.web7o.yandex.ru") NIL NIL NIL))
09-17 11:06:56.260  13059-16087/odesk.johnlife.glimpse I/System.out﹕ A4 OK Fetch completed.
09-17 11:06:56.345  13059-16087/odesk.johnlife.glimpse I/System.out﹕ A5 FETCH 1 (BODY[1]<0.9688>)
09-17 11:06:56.435  13059-16087/odesk.johnlife.glimpse I/System.out﹕ * 1 FETCH (FLAGS (\Seen \Recent) BODY[1]<0> {9688}

**Comment by Woffkaa** [comment]
Сделано
