### ISSUE TITLE
Протестировать автоудаление фоток при заполнении памяти

### ISSUE THREAD

**Issue by johnlife** [johnlife/Glimpse-Android#83]
Вручную забить место, оставить место под 15-20 фоток
Начать посылать фотографии, проверить что при забивании места самые ранние фотографии удаляются

**Comment by Woffkaa** [comment]
Работает

**Comment by johnlife** [comment]
Here is how we tested running out of memory:

On the testing memory max issue. I added a few very large files by doing "adb push file /mnt/sdcard/" until I could see that there were only a few MBs left in memory, then I sent pictures until the space ran out. 

My skylight (v3.7) did not delete the old pictures to make room for new ones. There are no notifications to the user or the sender that Skylight's memory is full. 

Is this also what you guys did? If so, could you test it again?

**Comment by Woffkaa** [comment]
Походу я пропустил момент, когда не хватило места записать в кеш. Там проверка не стоит, а стоит при записи файла в нашу папку. Перенесу проверку.

**Comment by Woffkaa** [comment]
По поводу расчёта размера фотки до записи в кеш.
Т.к. фотка ещё не раскодирована, то она весит на 33% больше, но можно проверять тип кодировки и умножать на 3/4, получая примерный размер(иногда расходится на 2 бита). Но это только для base64. А их там вроде ещё много. Я хотел посмотреть что с яндекса приходит, но фотки не приходят. Или не заморачиваться с кодировками и удалять под размер закодированной фотки?

**Comment by johnlife** [comment]
Не заморачиваться и удалять под ТРОЙНОЙ размер закодированной фотки
